#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "{BASH_SOURCE[0]}") && pwd)

ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

# mkdir -p $HOME/.local/bin
# rm -rf $HOME/.local/bin/t
# ln -s $DOTFILES/scripts/t $HOME/.local/bin/t
