filetype plugin indent on
syntax enable 

set autoindent                 
set expandtab
set shiftround
set shiftwidth=4
set tabstop=4
set smarttab

set backspace=indent,eol,start
set hidden                    
set incsearch                 
set smartcase
set ruler                     
set wildmenu                  
set colorcolumn=80
set number relativenumber

runtime macros/matchit.vim

let mapleader = ','

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" PLUGINS
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-vinegar'
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'mattn/emmet-vim'
Plug 'arcticicestudio/nord-vim'
Plug 'itchyny/lightline.vim'
Plug 'chrisbra/NrrwRgn'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'dense-analysis/ale'
call plug#end()

" Theme
colorscheme nord

" Lightline
set laststatus=2
let g:lightline = {
    \ 'colorscheme': 'nord',
    \ } 

" Fugitive
nnoremap <leader>gs :vertical Gstatus<cr>

" FZF
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }

nnoremap <silent> <leader>F :FZF<cr>
nnoremap <silent> <leader>GF :GFiles<cr>
nnoremap <silent> <leader>bu :Buffers<cr>

" Emmet
let g:user_emmet_leader_key='<C-]>'

" ALE
 let g:ale_linters = {
\    'javascript': ['eslint']
\}

let g:ale_fixers = {
\    'javascript': ['prettier', 'eslint'],
\    'scss': ['prettier'],
\    'html': ['prettier'],
\}

let g:ale_fix_on_save = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'

