filetype plugin indent on
syntax on

set autoindent                 
set expandtab
set shiftround
set shiftwidth=4
set tabstop=4
set smarttab

set backspace=indent,eol,start
set hidden                    
set incsearch                 
set smartcase
set ruler                     
set wildmenu                  
set colorcolumn=80
set number relativenumber

runtime macros/matchit.vim

let mapleader = ','

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" PLUGINS
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-vinegar'
call plug#end()

" Fugitive
nnoremap <leader>gs :vertical Gstatus<cr>
