# Bind prefix to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Toggle Status Line
bind-key t set-option status

# Vi Mode
set -g mode-keys vi
set -g status-keys vi

# Selection
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Fix for ESC delay
set -s escape-time 0

# Status Line
set -g status-style 'bg=blue,fg=#ffffff'

# Color the window tags
TMUX_COLORTAG_TAG_ONLY=yes
set -g @plugin 'Determinant/tmux-colortag'

# Open files/links
set -g @plugin 'tmux-plugins/tmux-open'

# Plugin Manager
run -b '~/.tmux/plugins/tpm/tpm'
