# Bind prefix to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Toggle Status Line
bind-key t set-option status

# Vi Mode
set -g mode-keys vi
set -g status-keys vi

# Fix for ESC delay
set -s escape-time 0

# Status Line
set -g status-style 'bg=blue,fg=#ffffff'

# Color the window tags
set -g @plugin 'Determinant/tmux-colortag'

# Plugin Manager
run -b '~/.tmux/plugins/tpm/tpm'
