# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$HOME/.composer/vendor/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
    git
    vi-mode
)

source $ZSH/oh-my-zsh.sh

alias zshconfig="vim ~/dotfiles/zsh/zshrc"

if type nvim > /dev/null 2>&1; then
	alias vim='nvim'
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
